# Generated by Django 2.2.5 on 2019-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rating', models.TextField()),
                ('genre', models.TextField()),
                ('runtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.TextField()),
                ('movie', models.ForeignKey(on_delete='PROTECT', to='app.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('purschase_at', models.TimeField()),
                ('showing', models.ForeignKey(on_delete='PROTECT', to='app.Showing')),
            ],
        ),
    ]
